### ISSUE TITLE
When will it be released？

### ISSUE THREAD

**Issue by JarintotionDin** [TMIU/iTFA#1]
I can't wait for it.

**Comment by 2252033991** [comment]
When will it be released

**Comment by snow102** [comment]
When will it be released? I would like to know ,too.

**Comment by hxhdnd** [comment]
When will it be released? I would like to know ,too.

**Comment by ZS-YANG** [comment]
When will it be released? I would like to know ,too.😆😆😆 @TMIU

**Comment by Morningstaripfy** [comment]
When will it be released? I would like to know ,too.

**Comment by crml233** [comment]
Hello, could you mind updating on when the code will be available for access? I'm eager to explore it further and would greatly appreciate your assistance.

Thank you very much for your time and consideration.

**Comment by crml233** [comment]
Hello @TMIU , could you mind updating on when the code will be available for access? I'm eager to explore it further and would greatly appreciate your assistance.

Thank you very much for your time and consideration.

**Comment by ningsummerw** [comment]
请问什么时候发布代码？
